# Generated by Django 3.0.7 on 2020-12-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BangaloreCameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BangaloreRowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
