# Generated by Django 3.0.7 on 2020-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location3CameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location3RowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location4CameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location4RowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location5CameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location5RowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location6CameraDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nvr_dvr', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('sum_total_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_baseline_days_rec', models.CharField(blank=True, max_length=50)),
                ('sum_of_storage_warning', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location6RowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_labels', models.CharField(max_length=100, null=True)),
                ('sum_of_no_of_channels', models.CharField(max_length=20)),
                ('sum_of_total_cameras', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='BangaloreCameraDashboard',
            new_name='Location1CameraDashboard',
        ),
        migrations.RenameModel(
            old_name='BangaloreRowLabel',
            new_name='Location1RowLabel',
        ),
        migrations.RenameModel(
            old_name='CameraDashboard',
            new_name='Location2CameraDashboard',
        ),
        migrations.RenameModel(
            old_name='RowLabel',
            new_name='Location2RowLabel',
        ),
    ]
