# Generated by Django 3.0.5 on 2020-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cameradashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradashboard',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cameradashboard',
            name='sum_of_baseline_days_rec',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cameradashboard',
            name='sum_of_storage_warning',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cameradashboard',
            name='sum_total_days_rec',
            field=models.CharField(max_length=50),
        ),
    ]
